trigger:
  - main

pool: 
 name: 'Azure Pipelines'     # ensure Linux path & toolcache
steps:
- task: TerraformTask@5
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/logicapp'   # <-- fix path + casing
    backendServiceArm: 'Myconnectionactive'
    backendAzureRmResourceGroupName: 'rg-dxDevUKWest'
    backendAzureRmStorageAccountName: 'demonewtestgroupb2e7'
    backendAzureRmContainerName: 'demonew'
    backendAzureRmKey: 'trf/terraform.tfstate'
    backendAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'

- task: TerraformTask@5
  displayName: 'terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/logicapp'

- task: TerraformTask@5
  displayName: 'terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/logicapp'
    commandOptions: '-lock=false'
    environmentServiceNameAzureRM: 'Myconnectionactive'
    environmentAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'

