trigger:
  - main

pool:
 name: 'Azure Pipelines'

stages:
  - stage: Terraform
    displayName: Terraform Build stage
    jobs:
    - job: Build
      displayName:  Terraform Build Job
      steps:
      - task: TerraformInstaller@1
        inputs: 
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendAzureRmUseEntraIdForAuthentication: false
          backendServiceArm: 'Myconnectionactive'
          backendAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'
          backendAzureRmResourceGroupName: 'rg-dxDevUKWest'
          backendAzureRmStorageAccountName: 'demonewtestgroupb2e7'
          backendAzureRmContainerName: 'demonew'
          backendAzureRmKey: 'trf/terraform.tfstate'
        
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-lock=false'
          environmentServiceNameAzureRM: 'Myconnectionactive'
          environmentAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '--auto-approve -lock=false'
          environmentServiceNameAzureRM: 'Myconnectionactive'
          environmentAzureRmOverrideSubscriptionID: '12486a52-70e3-4ae6-9f94-e6bacd147419'
      